"""add ip address column

Revision ID: 53c5acb3b17f
Revises: 52dcffd99d86
Create Date: 2017-08-13 18:14:32.740330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c5acb3b17f'
down_revision = '52dcffd99d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ip_address', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ip_address')
    # ### end Alembic commands ###
