"""add score column

Revision ID: 59993fa41bea
Revises: a38376dcc8ae
Create Date: 2017-08-24 10:39:49.981515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59993fa41bea'
down_revision = 'a38376dcc8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'score')
    # ### end Alembic commands ###
