"""add content column

Revision ID: 83ef3fcbf96f
Revises: 1c243796e75a
Create Date: 2017-08-12 03:01:11.211010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ef3fcbf96f'
down_revision = '1c243796e75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
